---
name: pull-request

on:
  pull_request:
    branches: [main, test, dev]
  push:
    branches: [cicd/add-pr-action]

jobs:
  yaml:
    name: yaml code validation
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install yamllint
        run: pip install --user yamllint

      - name: Linting
        run: yamllint .
  scan:
    name: tfsec scan
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17.0'

      - name: Install tfsec
        run: go install github.com/aquasecurity/tfsec/cmd/tfsec@latest

      - name: Scan code
        run: tfsec .
